In [14]:
import tensorflow as tf
print("Tensorflow version:{}".format(tf.__version__))

Tensorflow version:2.18.0


In [15]:
d0=tf.constant(1)
print("Dimension is ",tf.rank(d0).numpy())
print(d0)

Dimension is  0
tf.Tensor(1, shape=(), dtype=int32)


In [16]:
d1=tf.ones((2,))
print("Dimension is",tf.rank (d1).numpy())
print(d1)

Dimension is 1
tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [17]:
d2=tf.ones((2,2))
print("Dimension is",tf.rank (d2).numpy())
print(d2)

Dimension is 2
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [18]:
d3=tf.ones((2,2,2))
print("Dimension is",tf.rank (d3).numpy())
print(d3)

Dimension is 3
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [22]:
x1=tf.Variable(23)
x2=tf.Variable([[[0.,1.,2.],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]])
x0=123
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

In [24]:
x1.assign(100)
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>

In [28]:
x1=tf.Variable(100)
print(x1)
x1.assign(200)
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=200>

In [29]:
x2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [30]:
x0

123

Reshape

In [32]:
x112=tf.reshape(x2,[1,12])
x112

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

In [34]:
xf64=tf.Variable(202,dtype=tf.float64)
xf64.dtype

tf.float64

In [35]:
np.float64

NameError: name 'np' is not defined

Declaring Variable with Type

In [36]:
tf.rank(xf64)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [37]:
tf.rank(x2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [38]:
t=tf.constant([[[1,1,1],[2,2,2]],[[4,3,5],[4,4,414]]])
tf.rank(t).numpy()

np.int32(3)

In [39]:
t.numpy()

array([[[  1,   1,   1],
        [  2,   2,   2]],

       [[  4,   3,   5],
        [  4,   4, 414]]], dtype=int32)

Tensor Slicing

In [40]:
tensor3=t[1,1,2]
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=414>

In [43]:
x=tf.constant([0,1,1,2,3,4,8,13,21,34])
print("Before 4:",x[:4].numpy())
print("After 4",x [4:].numpy())
print("From 2,before 7",x[2:7].numpy())
print("Every other item:",x[::2].numpy())
print("Reversed:",x[::-1].numpy())

Before 4: [0 1 1 2]
After 4 [ 3  4  8 13 21 34]
From 2,before 7 [1 2 3 4 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  4  3  2  1  1  0]


Casting tensor to a datatype

In [47]:
a=tf.constant([[1,2],[3,4]])
i=tf.cast(a,dtype=tf.float32)
print(a)
print(i)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


Tensor Operation

In [48]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

c = a + b
print("Addition:\n", c.numpy())

d = tf.square(c)
print("Squared:\n", d.numpy())

e = tf.add(a, b)
f = tf.subtract(b, a)
g = tf.multiply(a, b)

print("Add:\n", e.numpy())
print("Subtract:\n", f.numpy())
print("Multiply:\n", g.numpy())


Addition:
 [[ 6  8]
 [10 12]]
Squared:
 [[ 36  64]
 [100 144]]
Add:
 [[ 6  8]
 [10 12]]
Subtract:
 [[4 4]
 [4 4]]
Multiply:
 [[ 5 12]
 [21 32]]
